image: google/cloud-sdk:178.0.0-alpine

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  only:
  - master

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server"
  only:
  - tags
